# Generated by Django 2.2.19 on 2021-03-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_remove_tempo_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempo',
            name='topic',
            field=models.CharField(default='goat', max_length=250),
        ),
    ]
